# Crypto Regime Analysis System Configuration

# =============================================================================
# Execution Configuration (Live Trading)
# =============================================================================
execution:
  # Alpaca (Paper + Live Trading)
  alpaca:
    enabled: true
    api_key: "PKPTS4BAZFLOZETRXZQ2SX2CJ7"
    api_secret: "B19BqEueb9E3nYc6B1aZvRWhYsVgyFQXXs3ZyV9W92m6"
  
  # Coinbase (Live Only)
  coinbase:
    enabled: true
    api_key: "organizations/96b7553d-65cc-4ea7-9846-6638c0ebc9c9/apiKeys/3deb12b7-ccf6-41b8-96c4-1000a27779c6"
    api_secret: "-----BEGIN EC PRIVATE KEY-----\\nMHcCAQEEIOsodBddfKIVEPwgAA3FAZYLmE0QPQGANGzRafNTpKhmoAoGCCqGSM49\\nAwEHoUQDQgAEaXpKWikKqdCrnElQwvTS5T1RRBWRloWyOoKINPo9TNswhU0j3YKi\\nfpb+gnifTTaEJkt9BmXxqWvZBarsUz35hA==\\n-----END EC PRIVATE KEY-----\\n"
  
  # Risk Management Limits
  max_position_size_pct: 0.20  # Max 20% per position
  max_exposure_pct: 0.95       # Max 95% total exposure
  max_positions: 10            # Max number of positions
  min_confidence: 0.50         # Min 50% confidence to trade

# =============================================================================
# Analysis Configuration
# =============================================================================

# Symbols to analyze
symbols:
  # Equities / ETFs
  - SPY
  
  # Crypto
  - BTC-USD
  - ETH-USD
  - SOL-USD
  - XRP-USD
  
  # Forex (for validation with longer history)
  - EUR-USD
  - GBP-USD
  - USD-JPY
  - AUD-USD
  - USD-CAD

data_source:
  equities: "alpaca"
  equities_feed: "iex"
  crypto_fx: "polygon"

# Timeframe definitions (tier-based)
timeframes:
  LT:  # Long-term / Macro
    bar: "1d"
    lookback: 1460  # 4 years for macro stability
    min_samples: 500
  MT:  # Medium-term / Swing
    bar: "4h"
    lookback: 360   # 12 months for cyclic context
    min_samples: 400
  ST:  # Short-term / Execution
    bar: "15m"
    lookback: 90    # Crypto/Forex get full 90 days; Equities limited to ~3 days (API restriction)
    min_samples: 50  # Lowered from 300 to work with limited equity intraday data (~80-250 bars)
  US:  # Ultra-short / Gate alignment
    bar: "5m"
    lookback: 30    # 10-30 days for gate confirmation
    min_samples: 300

# Execution-only microstructure buffer
execution_buffer:
  bar: "1m"
  lookback: 3   # 72 hours for liquidity/spread checks

# Hurst exponent computation settings
hurst:
  min_window: 16
  max_window: 512
  step: 2
  method: "both"  # "rs", "dfa", or "both"

# Statistical tests configuration
tests:
  variance_ratio_lags: [2, 5, 10]
  adf_alpha: 0.05
  adf_maxlag: null  # auto-select

# CCM (Cross-Asset Context) Agent configuration
ccm:
  enabled: true
  # Directed tiers where CCM will be evaluated
  tiers: ["LT", "MT", "ST"]
  tiers_for_ccm: ["ST", "MT"]

  # Directed asset pairs to evaluate (A leads B, and B leads A)
  pairs:
    - ["NVDA", "SPY"]
    - ["AAPL", "SPY"]
    - ["BTC-USD", "ETH-USD"]
    - ["EUR-USD", "USD-JPY"]

  # CCM parameters
  E: 3
  tau: 1
  lib_sizes: [50, 80, 120]
  min_points: 200

  # Interpretation thresholds
  rho_threshold: 0.25
  delta_threshold: 0.10
  top_n: 5

  # Legacy context configuration retained for compatibility
  context_symbols:
    - ETH-USD
    - SOL-USD
    - SPY
    - DXY
    - VIX
  params:
    E: 3
    tau: 1
    library_frac: 0.8
  thresholds:
    sector_strong: 0.60
    macro_low: 0.20

# Market Intelligence Agent configuration (Microstructure Analysis)
market_intelligence:
  enabled: true  # Enable microstructure analysis
  tiers: ["ST"]  # Focus on short-term for microstructure
  enhanced: true  # Enable enhanced estimators (Corwin-Schultz, Roll, Kyle, Amihud)

  # Microstructure features to compute
  features:
    bid_ask_spread: true
    order_flow_imbalance: true
    microprice: true
    price_impact: true
    trade_flow: true

  # OFI (Order Flow Imbalance) parameters
  ofi:
    window_sizes: [10, 25, 50]  # Multiple timeframes for OFI
    threshold: 0.1  # Minimum threshold for significant imbalance

  # Data requirements
  data:
    min_tick_bars: 1000  # Minimum tick bars needed for reliable microstructure
    max_spread_bps: 50  # Maximum spread in basis points to consider valid

  # LLM providers for dual-agent system
  llm:
    context_provider: "perplexity"  # For real-time market data
    analytical_provider: "openai"   # For deep analysis
  
  # Context symbols for cross-asset analysis
  context_symbols:
    - ETH-USD
    - SOL-USD
    - SPY      # S&P 500
    - DXY      # US Dollar Index
    - VIX      # Volatility Index
  
  # CCM computation parameters
  params:
    E: 3              # Embedding dimension
    tau: 1            # Time delay
    library_frac: 0.8 # Fraction of data for library
  
  # Thresholds for regime interpretation
  thresholds:
    sector_strong: 0.60   # High crypto-sector coupling
    macro_low: 0.20       # Low macro coupling = decoupled

equities:
  include_premarket: false
  include_postmarket: false
  tz: "America/New_York"
  adjustment: "all"
  # Data source: Use Alpaca (Polygon limits equity intraday to 3 days regardless of subscription)
  # Note: Both Alpaca and Polygon give ~3 days of equity intraday, Alpaca is free
  timeframes:
    MT:
      bar: "1h"
      lookback: 360

# Stochastic forecast settings for Monte Carlo outlook
stochastic_forecast:
  enabled: true
  num_paths: 2000
  quantiles: [0.05, 0.25, 0.5, 0.75, 0.95]
  seed: 42
  tiers:
    ST:
      horizon_bars: 78
      dt_per_bar_days: 0.0128205128  # ~5m bars
    MT:
      horizon_bars: 20
      dt_per_bar_days: 1.0
    LT:
      horizon_bars: 60
      dt_per_bar_days: 1.0
  estimation:
    drift: "mle"      # or "ema"
    vol: "realized"   # or "garch"
    ema_span: 20

# Backtest configuration
backtest:
  # Transaction costs (in basis points)
  costs:
    spread_bps: 5   # Bid-ask spread
    slip_bps: 3     # Slippage
    fee_bps: 2      # Exchange fee
  
  # Walk-forward settings
  train_frac: 0.7
  min_trades: 10
  
  # Simplified Strategy Framework (2 core strategies)
  # Regime-matched with ATR position sizing
  strategies:
    trending:
      - name: ma_cross
        params:
          fast: [10, 12, 16]
          slow: [26, 34, 50]
          atr_stop: [2.0, 2.5, 3.0]  # ATR-based stops
    mean_reverting:
      - name: bollinger_rsi
        params:
          bb_period: [15, 20, 25, 30]
          bb_std: [1.5, 2.0, 2.5]
          rsi_period: [10, 14, 20]
          rsi_oversold: [25, 30, 35]
          rsi_overbought: [65, 70, 75]
          atr_stop: [1.5, 2.0, 2.5]  # ATR-based stops
    random:
      - name: carry
        params: {}  # Don't backtest random regimes
    volatile_trending:
      - name: ma_cross
        params:
          fast: [8, 10]
          slow: [21, 26]
          atr_stop: [2.5, 3.0, 3.5]  # Wider stops for volatility

# Regime classification thresholds
# Adjusted for crypto market characteristics (more lenient)
regime:
  hurst_thresholds:
    mean_reverting: 0.48  # Adjusted from 0.45 (crypto is noisier)
    trending: 0.52         # Adjusted from 0.55 (tighter band)
  vr_thresholds:
    mean_reverting: 0.97   # Adjusted from 0.95
    trending: 1.03         # Adjusted from 1.05
  confidence_min: 0.50
  
  # Weighted voting system for regime classification
  signal_weights:
    hurst: 0.35      # 35% - primary signal
    vr: 0.25         # 25% - statistical confirmation
    acf: 0.20        # 20% - autocorrelation pattern (NEW!)
    adf: 0.15        # 15% - stationarity check
    volatility: 0.05 # 5% - market condition
  volatility_signal:
    realized_vol_threshold: 0.03  # Fallback threshold when GARCH unavailable
    garch_high_ratio: 1.25        # High-vol threshold supporting trend classification
    garch_low_ratio: 0.85         # Low-vol threshold supporting mean reversion

  hysteresis:
    enabled: true              # Require confirmation before regime flips
    confirmation_bars: 2       # Number of consecutive detections needed
    use_transition_state: true # Emit 'uncertain' regime while awaiting confirmation
    transition_confidence_cap: 0.35  # Cap confidence when in transition
  gating:
    enabled: true
    tiers:
      MT:
        enter: 0.60
        exit: 0.52
        m_bars: 2
        p0: 0.55
        k: 0.03
        floor: 0.50
        cap: 0.75
        min_remaining: 60
        sigma_ref_window: 240
      ST:
        enter: 0.58
        exit: 0.50
        m_bars: 3
        p0: 0.55
        k: 0.05
        floor: 0.50
        cap: 0.78
        min_remaining: 30
        sigma_ref_window: 200
      US:
        enter: 0.60
        exit: 0.52
        m_bars: 3
        p0: 0.55
        k: 0.06
        floor: 0.50
        cap: 0.80
        min_remaining: 15
        sigma_ref_window: 150
    volatility:
      method: "ewma"
      lambda: 0.94
      ref_floor: 0.0001
    posterior:
      a: 3.0
      b: -1.5
      margin_weight: 0.5
      volatility_weight: 0.2
      gate_penalty: 0.3
  multi_timeframe:
    enabled: true
    reference_tier: "MT"
    confirmation_tiers: ["ST", "US"]
    allow_reference_neutral: true
    min_reference_confidence: 0.55
    disagreement_policy: "defer"  # defer, allow, or override
  events:
    enabled: true
    tiers: ["ST", "US"]
    lead_minutes: 30
    trail_minutes: 60
    severity_floor: "high"

# Enhanced Tier Configuration
tiers:
  weights:
    LT: 0.30  # Long-term weight in fusion
    MT: 0.50  # Medium-term weight (primary)
    ST: 0.20  # Short-term weight
  windows:
    hurst_rolling: 100   # Window for rolling Hurst
    hurst_step: 20       # Step size for rolling calcs
    vr_lags: [2, 4, 8]   # Multiple lags for VR test

# Contradictor Agent settings
contradictor:
  enabled: true
  penalty_per_flag: 0.10  # Penalty per contradiction (transparent)
  alpha_vr: 0.05          # Significance level for VR
  alpha_alt: 0.05         # Significance for alternate tests
  alternate_bars:
    "15m": "1h"
    "1h": "15m"
    "4h": "1d"
    "1d": "4h"
  borderline_threshold: 0.10  # p-value closeness to alpha

# Regime Transition Analysis
transition:
  lookback_bars: 1000  # Bars for empirical transition matrix

# Volatility Clustering
volatility:
  garch:
    enabled: true
    min_samples: 200
    high_vol_ratio: 1.25
    low_vol_ratio: 0.85

technical_levels:
  pivot_lookback: 20
  donchian_lookback: 20
  atr_period: 14
  arch_lm_lags: 5  # Lags for ARCH-LM test
  garch:
    enabled: true
    min_samples: 200
    high_vol_ratio: 1.25
    low_vol_ratio: 0.85

# Report Generation
report:
  show_charts: true       # Generate visualizations
  save_charts: true       # Save to charts/ directory
  chart_width: 900        # pixels
  chart_height: 320       # pixels
  sandbox_web_summary: true  # Label Perplexity as "Non-Model"

# Feature flags for transition telemetry and adaptive hysteresis
features:
  transition_metrics:
    enabled: true
    # New per-tier window bars; orchestrator falls back to legacy shape if present
    window_bars:
      LT: 1000
      MT: 1656
      ST: 500   # Lowered from 1689 to work with limited equity intraday (Polygon gives ~1850 bars)
      US: 500   # Lowered from 1729 for consistency
    sigma_window: 5
    persist_labels: true
    persist_dir: "artifacts/warmstart"
    # Backward-compat fields still honored if present
    persist: true
    backfill_on_boot: true
    files:
      dir: "metrics"

  adaptive_hysteresis:
    enabled: true
    shadow_mode: false
    clamps:
      m_bars_min: 2
      m_bars_max: 8
      enter_pp_max: 0.03
      exit_pp_max: 0.03
    formulas:
      m_bars_factor: 0.25
      enter_pp_per_z: 0.01
      exit_pp_per_z: 0.01

# Risk Management
risk:
  confidence_bands: [0.50, 0.75]  # Map to position sizing
  # <50%: stay flat or 25% position
  # 50-75%: 50% position
  # >75%: full position

# Telegram bot configuration
telegram:
  enabled: true
  allowed_user_ids:
    - 123456789  # Replace with your Telegram user ID
  commands:
    - analyze
    - status
  rate_limit_seconds: 30

# Output configuration
output:
  artifacts_dir: "./artifacts"
  timezone: "UTC"
  save_plots: true
  save_csv: true
  report_format: "markdown"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/regime_detector.log"

# QuantConnect Integration (optional)
lean:
  export_signals: true  # Enable to write signals.csv for Lean consumption
  signals_dir: "data/signals"

qc:
  auto_submit: false  # Disable QC auto-submit for now (set true when ready)
  wait_for_results: false  # Set to true to wait (adds 5-10 min), false to run in background
  timeout_seconds: 300  # Max wait time if wait_for_results = true
