# Crypto Regime Analysis System Configuration

# =============================================================================
# Execution Configuration (Live Trading)
# =============================================================================
execution:
  # Alpaca (Paper + Live Trading)
  alpaca:
    enabled: true
    api_key: "PKPTS4BAZFLOZETRXZQ2SX2CJ7"
    api_secret: "B19BqEueb9E3nYc6B1aZvRWhYsVgyFQXXs3ZyV9W92m6"
  
  # Coinbase (Live Only)
  coinbase:
    enabled: true
    api_key: "organizations/96b7553d-65cc-4ea7-9846-6638c0ebc9c9/apiKeys/3deb12b7-ccf6-41b8-96c4-1000a27779c6"
    api_secret: "-----BEGIN EC PRIVATE KEY-----\\nMHcCAQEEIOsodBddfKIVEPwgAA3FAZYLmE0QPQGANGzRafNTpKhmoAoGCCqGSM49\\nAwEHoUQDQgAEaXpKWikKqdCrnElQwvTS5T1RRBWRloWyOoKINPo9TNswhU0j3YKi\\nfpb+gnifTTaEJkt9BmXxqWvZBarsUz35hA==\\n-----END EC PRIVATE KEY-----\\n"
  
  # Risk Management Limits
  max_position_size_pct: 0.20  # Max 20% per position
  max_exposure_pct: 0.95       # Max 95% total exposure
  max_positions: 10            # Max number of positions
  min_confidence: 0.50         # Min 50% confidence to trade

# =============================================================================
# Analysis Configuration
# =============================================================================

# Symbols to analyze
symbols:
  # Crypto
  - BTC-USD
  - ETH-USD
  - SOL-USD
  - XRP-USD
  
  # Forex (for validation with longer history)
  - EUR-USD
  - GBP-USD
  - USD-JPY
  - AUD-USD
  - USD-CAD

# Timeframe definitions (tier-based)
timeframes:
  LT:  # Long-term / Macro
    bar: "1d"
    lookback: 730  # ~2 years
    min_samples: 300
  MT:  # Medium-term / Swing
    bar: "4h"
    lookback: 120  # ~120 days
    min_samples: 300
  ST:  # Short-term / Execution
    bar: "15m"
    lookback: 30  # ~30 days
    min_samples: 300

# Hurst exponent computation settings
hurst:
  min_window: 16
  max_window: 512
  step: 2
  method: "both"  # "rs", "dfa", or "both"

# Statistical tests configuration
tests:
  variance_ratio_lags: [2, 5, 10]
  adf_alpha: 0.05
  adf_maxlag: null  # auto-select

# CCM (Cross-Asset Context) Agent configuration
# DISABLED: Data access issues with ETH-USD, SOL-USD, DXY, VIX
ccm:
  enabled: false  # Disabled - insufficient data access
  tiers: ["LT", "MT", "ST"]

# Market Intelligence Agent configuration (Microstructure Analysis)
market_intelligence:
  enabled: true  # Enable microstructure analysis
  tiers: ["ST"]  # Focus on short-term for microstructure

  # Microstructure features to compute
  features:
    bid_ask_spread: true
    order_flow_imbalance: true
    microprice: true
    price_impact: true
    trade_flow: true

  # OFI (Order Flow Imbalance) parameters
  ofi:
    window_sizes: [10, 25, 50]  # Multiple timeframes for OFI
    threshold: 0.1  # Minimum threshold for significant imbalance

  # Data requirements
  data:
    min_tick_bars: 1000  # Minimum tick bars needed for reliable microstructure
    max_spread_bps: 50  # Maximum spread in basis points to consider valid

  # LLM providers for dual-agent system
  llm:
    context_provider: "perplexity"  # For real-time market data
    analytical_provider: "openai"   # For deep analysis
  
  # Context symbols for cross-asset analysis
  context_symbols:
    - ETH-USD
    - SOL-USD
    - SPY      # S&P 500
    - DXY      # US Dollar Index
    - VIX      # Volatility Index
  
  # CCM computation parameters
  params:
    E: 3              # Embedding dimension
    tau: 1            # Time delay
    library_frac: 0.8 # Fraction of data for library
  
  # Thresholds for regime interpretation
  thresholds:
    sector_strong: 0.60   # High crypto-sector coupling
    macro_low: 0.20       # Low macro coupling = decoupled

# Backtest configuration
backtest:
  # Transaction costs (in basis points)
  costs:
    spread_bps: 5   # Bid-ask spread
    slip_bps: 3     # Slippage
    fee_bps: 2      # Exchange fee
  
  # Walk-forward settings
  train_frac: 0.7
  min_trades: 10
  
  # Strategy templates per regime
  # Multiple strategies will be tested for each regime
  # System will select best performing one
  strategies:
    trending:
      - name: ma_cross
        params:
          fast: [10, 20]
          slow: [30, 50]
      - name: ema_cross
        params:
          fast: [8, 12]
          slow: [21, 26]
      - name: macd
        params:
          fast: [12]
          slow: [26]
          signal: [9]
      - name: donchian
        params:
          lookback: [20, 40]
    mean_reverting:
      - name: bollinger_revert
        params:
          window: [20]
          num_std: [2.0, 2.5]
      - name: rsi
        params:
          period: [14]
          oversold: [20, 30]
          overbought: [70, 80]
      - name: keltner
        params:
          period: [20]
          atr_mult: [2.0]
      - name: pairs_mean_reversion
        enabled: false  # Enable and set benchmark_symbol per asset to activate
        params:
          benchmark_symbol: ["X:ETHUSD"]
          benchmark_bar: ["4h"]
          lookback: [60]
          entry_z: [1.5]
          exit_z: [0.5]
    random:
      - name: carry
        params: {}
    volatile_trending:
      - name: atr_trend
        params:
          ma_period: [20]
          atr_period: [14]
          atr_mult: [2.0]
      - name: donchian
        params:
          lookback: [20, 30]
      - name: atr_trailing_stop
        params:
          ema_period: [21, 34]
          atr_period: [14]
          atr_mult: [2.5, 3.0]

# Regime classification thresholds
# Adjusted for crypto market characteristics (more lenient)
regime:
  hurst_thresholds:
    mean_reverting: 0.48  # Adjusted from 0.45 (crypto is noisier)
    trending: 0.52         # Adjusted from 0.55 (tighter band)
  vr_thresholds:
    mean_reverting: 0.97   # Adjusted from 0.95
    trending: 1.03         # Adjusted from 1.05
  confidence_min: 0.50
  
  # Weighted voting system for regime classification
  signal_weights:
    hurst: 0.35      # 35% - primary signal
    vr: 0.25         # 25% - statistical confirmation
    acf: 0.20        # 20% - autocorrelation pattern (NEW!)
    adf: 0.15        # 15% - stationarity check
    volatility: 0.05 # 5% - market condition
  volatility_signal:
    realized_vol_threshold: 0.03  # Fallback threshold when GARCH unavailable
    garch_high_ratio: 1.25        # High-vol threshold supporting trend classification
    garch_low_ratio: 0.85         # Low-vol threshold supporting mean reversion

  hysteresis:
    enabled: true              # Require confirmation before regime flips
    confirmation_bars: 2       # Number of consecutive detections needed
    use_transition_state: true # Emit 'uncertain' regime while awaiting confirmation
    transition_confidence_cap: 0.35  # Cap confidence when in transition

# Enhanced Tier Configuration
tiers:
  weights:
    LT: 0.30  # Long-term weight in fusion
    MT: 0.50  # Medium-term weight (primary)
    ST: 0.20  # Short-term weight
  windows:
    hurst_rolling: 100   # Window for rolling Hurst
    hurst_step: 20       # Step size for rolling calcs
    vr_lags: [2, 4, 8]   # Multiple lags for VR test

# Contradictor Agent settings
contradictor:
  enabled: true
  penalty_per_flag: 0.10  # Penalty per contradiction (transparent)
  alpha_vr: 0.05          # Significance level for VR
  alpha_alt: 0.05         # Significance for alternate tests
  alternate_bars:
    "15m": "1h"
    "1h": "15m"
    "4h": "1d"
    "1d": "4h"
  borderline_threshold: 0.10  # p-value closeness to alpha

# Regime Transition Analysis
transition:
  lookback_bars: 1000  # Bars for empirical transition matrix

# Volatility Clustering
volatility:
  garch:
    enabled: true
    min_samples: 200
    high_vol_ratio: 1.25
    low_vol_ratio: 0.85

technical_levels:
  pivot_lookback: 20
  donchian_lookback: 20
  atr_period: 14
  arch_lm_lags: 5  # Lags for ARCH-LM test
  garch:
    enabled: true
    min_samples: 200
    high_vol_ratio: 1.25
    low_vol_ratio: 0.85

# Report Generation
report:
  show_charts: true       # Generate visualizations
  save_charts: true       # Save to charts/ directory
  chart_width: 900        # pixels
  chart_height: 320       # pixels
  sandbox_web_summary: true  # Label Perplexity as "Non-Model"

# Risk Management
risk:
  confidence_bands: [0.50, 0.75]  # Map to position sizing
  # <50%: stay flat or 25% position
  # 50-75%: 50% position
  # >75%: full position

# Telegram bot configuration
telegram:
  enabled: true
  allowed_user_ids:
    - 123456789  # Replace with your Telegram user ID
  commands:
    - analyze
    - status
  rate_limit_seconds: 30

# Output configuration
output:
  artifacts_dir: "./artifacts"
  timezone: "UTC"
  save_plots: true
  save_csv: true
  report_format: "markdown"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/regime_detector.log"

# QuantConnect Integration (optional)
lean:
  export_signals: true  # Enable to write signals.csv for Lean consumption
  signals_dir: "data/signals"

qc:
  auto_submit: false  # Disable QC auto-submit for now (set true when ready)
  wait_for_results: false  # Set to true to wait (adds 5-10 min), false to run in background
  timeout_seconds: 300  # Max wait time if wait_for_results = true
